### ISSUE TITLE
Ошибка с кэшем

### ISSUE THREAD

**Issue by fortunto2** [vgrish/virtualpage#5]
Привет, иногда на главной отваливается все 
и выдает ошибку...

```

Fatal error: Uncaught exception 'RuntimeException' with message 'Invalid cache file 
"/var/www/life2film/www/core/cache/default/virtualpage/event//OnPageNotFound.cache.php"' 
in /var/www/life2film/www/core/components/virtualpage/model/lib/fastroute/src/functions.php:51 Stack trace: 


#0 /var/www/life2film/www/core/components/virtualpage/model/virtualpage/virtualpage.class.php(225):
 FastRoute\cachedDispatcher(Object(Closure), Array) #1 
 /var/www/life2film/www/core/components/virtualpage/model/virtualpage/virtualpage.class.php(101): 
 virtualpage->getDispatcher() #2 /var/www/life2film/www/core/cache/includes/elements/modplugin/26.include.cache.php(23): 
 virtualpage->doRoutes(Array) #3 /var/www/life2film/www/core/model/modx/modscript.class.php(70): 
 include('/var/www/life2f...') #4 /var/www/life2film/www/core/model/modx/modx.class.php(1613):
  modScript->process(Array) #5 /var/www/life2film/www/core/model/modx/modx.class.php(1188):
   modX->invokeEvent('OnPageNotFound', Array) 
   #6 /var/www/life2film/www/core/model/modx/modrequest.class.php in 
   /var/www/life2film/www/core/components/virtualpage/model/lib/fastroute/src/functions.php on line 51
```

версия 1.09 , буду обновлять 
и отлавливать опять

**Comment by vgrish** [comment]
с той поры много чего изменилось.
Сначала обновись а потом посмотри будет ли ошибка.
Спасибо!

**Comment by fortunto2** [comment]
а с репозитория в админке не обновиться с 1.09 на 2 ветку? 
у меня как будто нет новых версий...
в ручную ставить?

**Comment by vgrish** [comment]
наверно у тебя старая версия modx - потому и не показывает новую.
обновиться не получится, надо сначала деинсталировать старую, затем установить новую.

**Comment by fortunto2** [comment]
понятно спасибо

**Comment by vgrish** [comment]
пожалуйста. Отпиши по ошибке.
Спасибо!

**Comment by fortunto2** [comment]
обновил модекс... но в установщике приложение, так и нет новой версии. только 1.09
пытаюсь вручную ставить, билдер выдает ошибку

```

....
[2016-11-16 16:16:01] (INFO @ /var/www/****/www/core/packages/virtualpage-2.0.4-beta/modCategory/3b84fdc9e80fd390660907c4e0f5ab20.validate.vendors.validator : 37) Could not create directory: /var/www/weblife2film/www/core/components/virtualpage/vendor/
[2016-11-16 16:16:01] (INFO @ /var/www/***/www/core/packages/virtualpage-2.0.4-beta/modCategory/3b84fdc9e80fd390660907c4e0f5ab20.validate.vendors.validator : 47) Trying to download fastroute. Please wait...
[2016-11-16 16:16:02] (INFO @ /var/www/****/www/core/packages/virtualpage-2.0.4-beta/modCategory/3b84fdc9e80fd390660907c4e0f5ab20.validate.vendors.validator : 72) Could not extract fastroute from fastroute.zip to /var/www/weblife2film/www/core/components/virtualpage/vendor/. Error: Missing archive file '/var/www/****/www/core/components/virtualpage/vendor/fastroute.zip' [code -4]
```

**Comment by fortunto2** [comment]
а блин, прова не проверил на папку... скачалось
